module.exports = {
  createReelService: require("./createReel"),
  promoteReelService: require("./promoteReel"),
  editReelService: require("./editReel"),
  editReelPromotionService: require("./editReelPromotion"),
  incrementReelViewsService: require("./incrementReelViews"),
  toggleLikeService: require("./toggleLike"),
  commentsService: require("./comments"),
  getAllReelsService: require("./getAllReels"),
  getUserReelsService: require("./getUserReels"),
  getPromotedReelsService: require("./getPromotedReels"),
  deleteReelService: require("./deleteReel"),
  createReelUserService: require("./createReelUser"),
  editReelUserService: require("./editReelUser"),
  editReelsNotificationSettingsService: require("./editReelsNotificationSettings"),
  createReelsNotificationService: require("./createReelsNotification"),
  markReelsNotificationAsReadService: require("./markReelsNotificationAsRead"),
  getReelsNotificationsService: require("./getReelsNotifications"),
  getReelUserProfileService: require("./getReelUserProfile"),
  getPaginatedUserReelsService: require("./getPaginatedUserReels"),
  likeUserPageService: require("./likeUserPage"),
  unLikeUserPageService: require("./unlikeUserPage"),
  followUserService: require("./followUser"),
  unfollowUserService: require("./unfollowUser"),
};
